# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
